"""init database

Revision ID: 9303d945d14a
Revises: 
Create Date: 2026-06-16 11:12:00.939557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9303d945d14a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('distributors',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('STANDARD', 'THREE_D', 'IMAX', 'FOUR_DX', name='room_type'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('films',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('director', sa.String(length=100), nullable=False),
    sa.Column('actors', sa.String(length=255), nullable=True),
    sa.Column('min_duration', sa.Integer(), nullable=False),
    sa.Column('genre', sa.Enum('ACTION', 'AVENTURE', 'COMEDIE', 'DRAME', 'HORREUR', 'SCIENCE_FICTION', 'THRILLER', 'ANIMATION', 'DOCUMENTAIRE', 'ROMANCE', 'FANTASTIQUE', 'POLICIER', 'HISTORIQUE', 'MUSICAL', name='film_genre'), nullable=False),
    sa.Column('classification', sa.Enum('TOUS_PUBLICS', 'MOINS_10', 'MOINS_12', 'MOINS_16', 'MOINS_18', name='film_classification'), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('poster_url', sa.String(length=500), nullable=True),
    sa.Column('id_distributor', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_distributor'], ['distributors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.Enum('MENSUEL', 'ANNUEL', 'ILLIMITE', name='sub_plan'), nullable=False),
    sa.Column('price_monthly', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'CANCELLED', name='sub_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distribution_contracts',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.String(length=50), nullable=True),
    sa.Column('end_at', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seances',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.String(length=50), nullable=True),
    sa.Column('end_at', sa.String(length=50), nullable=True),
    sa.Column('format', sa.Enum('VF', 'VO', 'VOSTFR', name='seance_format'), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'OPEN', 'CLOSED', 'FULL', 'CANCELLED', name='seance_status'), nullable=True),
    sa.Column('seats_sold', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['films.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('seance_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('booking_ref', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'REFUNDED', 'USED', name='res_status'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('booked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['seance_id'], ['seances.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('royalty_tiers',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['distribution_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_statements',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('gross_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('royalty_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('royalty_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATED', 'INVOICED', 'PAID', name='statement_status'), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['distribution_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('distributor_id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('amount_ht', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_ttc', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ISSUED', 'PAID', 'OVERDUE', 'CANCELLED', name='invoice_status'), nullable=False),
    sa.ForeignKeyConstraint(['distributor_id'], ['distributors.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['weekly_statements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), sa.Identity(always=True), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('ticket_type', sa.String(length=50), nullable=True),
    sa.Column('seat_number', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('invoices')
    op.drop_table('weekly_statements')
    op.drop_table('royalty_tiers')
    op.drop_table('reservations')
    op.drop_table('seances')
    op.drop_table('distribution_contracts')
    op.drop_table('subscriptions')
    op.drop_table('films')
    op.drop_table('rooms')
    op.drop_table('distributors')
    op.drop_table('clients')
    # ### end Alembic commands ###
